server.port=${PORT:${SERVER_PORT:8081}}

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5400/CafeWork?stringtype=unspecified}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none

brevo.api-key=${BREVO_API_KEY:}
brevo.from-email=${BREVO_FROM_EMAIL:}
brevo.from-name=${BREVO_FROM_NAME:CafeWork}

management.endpoint.health.probes.enabled=true
management.health.livenessstate.enabled=true
management.health.readinessstate.enabled=true
